secretfy_template:
  secret: /Users/s0s0249/workspace/open_source/secretfy-template-creator/secretfy_template/res/secrets.json
  template: /Users/s0s0249/workspace/open_source/secretfy-template-creator/secretfy_template/res/example.yaml.mustache
  extension: yaml
